Repository dylanlott/ravel, pull requests merged in 2020-04, with the labels that each got.

#18 Track outs
  api/__init__.py
  api/db.sqlite
  api/models/trackOuts.py
  api/models/wavFile.py
  api/requirements.txt
  api/routes/trackOuts.py
  api/routes/wavFile.py
Labels: back end, feature, python

#20 removes sqlite database from git
  .gitignore
Labels: back end, enhancement

#19 Jwt auth
  .DS_Store
  api/__init__.py
  api/db.sqlite
  api/routes/auth.py
  api/routes/main.py
  api/routes/track.py
  api/routes/user.py
  ui/package.json
  ui/src/App.vue
  ui/src/api/index.js
  ui/src/components/Navbar.vue
  ui/src/main.js
  ui/src/router.js
  ui/src/store/auth.js
  ui/src/store/index.js
  ui/src/views/Login.vue
  ui/src/views/NewQuote.vue
  ui/src/views/Signup.vue
  ui/yarn.lock
Labels: back end, enhancement, feature, python
